project_id = "qvgdltpydsoapvjzeiih"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"

[functions.process-manual-text]
verify_jwt = true

[functions.extract-pdf]
verify_jwt = true

[functions.categorize-document]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.chat-answer]
verify_jwt = true

[functions.query-index]
verify_jwt = true

[functions.reindex-product]
verify_jwt = true

[functions.reprocess-failed-documents]
verify_jwt = true

[functions.migrate-documents]
verify_jwt = true

[functions.delete-document]
verify_jwt = true

[functions.coen-chat]
verify_jwt = true

[functions.batch-process-embeddings]
verify_jwt = true

[functions.reprocess-documents]
verify_jwt = true

[functions.rerank]
verify_jwt = true

[functions.enhanced-search]
verify_jwt = true