// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvgdltpydsoapvjzeiih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Z2RsdHB5ZHNvYXB2anplaWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzIzNjYsImV4cCI6MjA2OTA0ODM2Nn0.hHal4IUeeoyIvSeLF7vR27emnjwsEjU9U8u_iPLmxd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});